source 'http://rubygems.org'

gem 'rails', '3.0.6'

# gem 'mysql2'

# Use unicorn as the web server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'ruby-debug'

# Bundle the extra gems:
# gem 'nokogiri'
#if defined?(JRUBY_VERSOIN)
   gem 'jdbc-sqlite3'
   gem 'activerecord-jdbc-adapter'
   gem 'activerecord-jdbcsqlite3-adapter'
   gem 'jruby-openssl'
   gem 'jruby-rack'
   gem 'warbler'
#else
#
#   gem 'sqlite3-ruby', :require => 'sqlite3'
#end
gem 'oa-oauth','=0.1.6', :require => 'omniauth/oauth'
gem 'jquery-rails', '>= 0.2.6'
gem 'fb_graph', '=1.6.2'
gem 'resque'
#gem 'SystemTimer'

# gem 'aws-s3', :require => 'aws/s3'

# Bundle gems for the local environment. Make sure to
# put test-only gems in this group so their generators
# and rake tasks are available in development mode:
# group :development, :test do
#   gem 'webrat'
# end
