# encoding: UTF-8
hebrew = 'עברית'

# 7 -very happy
# 6 - twink
# 5 - happy
# 4 - ok
# 3 - sad
# 2 - very sad
# 1 - angry
{
  :smileys=>{')):'=>2, '))):'=>2, '))-:'=>2, ')))-:'=>2,':))'=>7, ':)))'=>7, '((:'=>7, '(((:'=>7, ':-))'=>7, ':-)))'=>7,'=)'=>5,':-)'=>5,':)'=>5,'=('=>3,':-('=>3,':('=>3,':-t'=>1,'X('=>1,':-@'=>1,'>:('=>1,';)'=>6,'(;'=>6,'(-;'=>6,';-)'=>7},
  'happy' => {:v=>5,'not'=>3,'very'=>7},
  'blessed' => {:v=>5,'not'=>3,'very'=>7},
  'blissful' => {:v=>5,'not'=>3,'very'=>7},
  'blithe' => {:v=>5,'not'=>3,'very'=>7},
  'cheerful'=> {:v=>5,'not'=>3,'very'=>7},
  'chipper'=> {:v=>5,'not'=>3,'very'=>7},
  'chirpy'=> {:v=>5,'not'=>3,'very'=>7},
  'content'=> {:v=>5,'not'=>3,'very'=>7},
  'contented'=> {:v=>5,'not'=>3,'very'=>7},
  'convivial'=> {:v=>5,'not'=>3,'very'=>7},
  'delighted'=> {:v=>5,'not'=>3,'very'=>7},
  'ecstatic'=> {:v=>5,'not'=>3,'very'=>7},
  'elated'=> {:v=>5,'not'=>3,'very'=>7},
  'exultant'=> {:v=>5,'not'=>3,'very'=>7},
  'glad'=> {:v=>5,'not'=>3,'very'=>7},
  'gleeful'=> {:v=>5,'not'=>3,'very'=>7},
  'gratified'=> {:v=>5,'not'=>3,'very'=>7},
  'intoxicated'=> {:v=>5,'not'=>3,'very'=>7},
  'jolly'=> {:v=>5,'not'=>3,'very'=>7},
  'joyful'=> {:v=>5,'not'=>3,'very'=>7},
  'joyous'=> {:v=>5,'not'=>3,'very'=>7},
  'jubilant'=> {:v=>5,'not'=>3,'very'=>7},
  'light'=> {:v=>5,'not'=>3,'very'=>7},
  'lively'=> {:v=>5,'not'=>3,'very'=>7},
  'merry'=> {:v=>5,'not'=>3,'very'=>7},
  'mirthful'=> {:v=>5,'not'=>3,'very'=>7},
  'overjoyed'=> {:v=>5,'not'=>3,'very'=>7},
  'peaceful'=> {:v=>5,'not'=>3,'very'=>7},
  'peppy'=> {:v=>5,'not'=>3,'very'=>7},
  'perky'=> {:v=>5,'not'=>3,'very'=>7},
  'playful'=> {:v=>5,'not'=>3,'very'=>7},
  'pleasant'=> {:v=>5,'not'=>3,'very'=>7},
  'pleased'=> {:v=>5,'not'=>3,'very'=>7},
  'sparkling'=> {:v=>5,'not'=>3,'very'=>7},
  'sunny'=> {:v=>5,'not'=>3,'very'=>7},
  'thrilled'=> {:v=>5,'not'=>3,'very'=>7},
  'tickled'=> {:v=>5,'not'=>3,'very'=>7},
  'ok' => {:v=>4,'not'=>3},
  'sad' => {:v=>3,'not'=>4,'very'=>2},
  'unhappy'=> {:v=>3,'not'=>4,'very'=>2},
  'bereaved'=> {:v=>3,'not'=>4,'very'=>2},
  'bitter'=> {:v=>3,'not'=>4,'very'=>2},
  'blue'=> {:v=>3,'not'=>4,'very'=>2},
  'cheerless'=> {:v=>3,'not'=>4,'very'=>2},
  'dejected'=> {:v=>3,'not'=>4,'very'=>2},
  'despairing'=> {:v=>3,'not'=>4,'very'=>2},
  'despondent'=> {:v=>3,'not'=>4,'very'=>2},
  'disconsolate'=> {:v=>3,'not'=>4,'very'=>2},
  'dismal'=> {:v=>3,'not'=>4,'very'=>2},
  'distressed'=> {:v=>3,'not'=>4,'very'=>2},
  'doleful'=> {:v=>3,'not'=>4,'very'=>2},
  'down'=> {:v=>3,'not'=>4,'very'=>2},
  'downcast'=> {:v=>3,'not'=>4,'very'=>2},
  'forlorn'=> {:v=>3,'not'=>4,'very'=>2},
  'gloomy'=> {:v=>3,'not'=>4,'very'=>2},
  'glum'=> {:v=>3,'not'=>4,'very'=>2},
  'grief-stricken'=> {:v=>3,'not'=>4,'very'=>2},
  'grieved'=> {:v=>3,'not'=>4,'very'=>2},
  'heartbroken'=> {:v=>3,'not'=>4,'very'=>2},
  'heartsick'=> {:v=>3,'not'=>4,'very'=>2},
  'heavyhearted'=> {:v=>3,'not'=>4,'very'=>2},
  'hurting'=> {:v=>3,'not'=>4,'very'=>2},
  #in doldrums, in grief, in the dumps,
  'languishing'=> {:v=>3,'not'=>4,'very'=>2},
  'low'=> {:v=>3,'not'=>4,'very'=>2},
  'low-spirited'=> {:v=>3,'not'=>4,'very'=>2},
  'lugubrious'=> {:v=>3,'not'=>4,'very'=>2},
  'melancholy'=> {:v=>3,'not'=>4,'very'=>2},
  'morbid'=> {:v=>3,'not'=>4,'very'=>2},
  'morose'=> {:v=>3,'not'=>4,'very'=>2},
  'mournful'=> {:v=>3,'not'=>4,'very'=>2},
  'pensive'=> {:v=>3,'not'=>4,'very'=>2},
  'pessimistic'=> {:v=>3,'not'=>4,'very'=>2},
  'somber'=> {:v=>3,'not'=>4,'very'=>2},
  'sorrowful'=> {:v=>3,'not'=>4,'very'=>2},
  'sorry'=> {:v=>3,'not'=>4,'very'=>2},
  'troubled'=> {:v=>3,'not'=>4,'very'=>2},
  'weeping'=> {:v=>3,'not'=>4,'very'=>2},
  'wistful'=> {:v=>3,'not'=>4,'very'=>2},
  'woebegone'=> {:v=>3,'not'=>4,'very'=>2},
  'angry' => {:v=>1,'not'=>2},
   'affronted'=> {:v=>1,'not'=>2},
   'annoyed'=> {:v=>1,'not'=>2},
   'antagonized'=> {:v=>1,'not'=>2},
   'chafed'=> {:v=>1,'not'=>2},
   'choleric'=> {:v=>1,'not'=>2},
   'convulsed'=> {:v=>1,'not'=>2},
   'cross'=> {:v=>1,'not'=>2},
   'upset'=>{:v=>3,'very'=>2,'not'=>4},
   'displeased'=> {:v=>1,'not'=>2},
   'enraged'=> {:v=>1,'not'=>2},
   'exacerbated'=> {:v=>1,'not'=>2},
   'exasperated'=> {:v=>1,'not'=>2},
   'ferocious'=> {:v=>1,'not'=>2},
   'fierce'=> {:v=>1,'not'=>2},
   'fiery'=> {:v=>1,'not'=>2},
   'fuming'=> {:v=>1,'not'=>2},
   'furious'=> {:v=>1,'not'=>2},
   'galled'=> {:v=>1,'not'=>2},
   'hateful'=> {:v=>1,'not'=>2},
   'heated'=> {:v=>1,'not'=>2},
   'hot'=> {:v=>1,'not'=>2},
   'huffy'=> {:v=>1,'not'=>2},
   'ill-tempered'=> {:v=>1,'not'=>2},
   'impassioned'=> {:v=>1,'not'=>2},
   'incensed'=> {:v=>1,'not'=>2},
   'indignant'=> {:v=>1,'not'=>2},
   'inflamed'=> {:v=>1,'not'=>2},
   'infuriated'=> {:v=>1,'not'=>2},
   'irascible'=> {:v=>1,'not'=>2},
   'irate'=> {:v=>1,'not'=>2},
   'ireful'=> {:v=>1,'not'=>2},
   'irritable'=> {:v=>1,'not'=>2},
   'irritated'=> {:v=>1,'not'=>2},
   'maddened'=> {:v=>1,'not'=>2},
   'nettled'=> {:v=>1,'not'=>2},
   'offended'=> {:v=>1,'not'=>2},
   'outraged'=> {:v=>1,'not'=>2},
   'piqued'=> {:v=>1,'not'=>2},
   'provoked'=> {:v=>1,'not'=>2},
   'raging'=> {:v=>1,'not'=>2},
   'resentful'=> {:v=>1,'not'=>2},
   'riled'=> {:v=>1,'not'=>2},
   'sore'=> {:v=>1,'not'=>2},
   'splenetic'=> {:v=>1,'not'=>2},
   'storming'=> {:v=>1,'not'=>2},
   'sulky'=> {:v=>1,'not'=>2},
   'sullen'=> {:v=>1,'not'=>2},
   'tumultous'=> {:v=>1,'not'=>2},
   'tumultuous'=> {:v=>1,'not'=>2},
   'turbulent'=> {:v=>1,'not'=>2},
   'uptight'=> {:v=>1,'not'=>2},
   'vexed'=> {:v=>1,'not'=>2},
   'wrathful'=> {:v=>1,'not'=>2},
   'bummed'=> {:v=>2},
   'pissed'=> {:v=>1},
    'finally'=> {:v=>5},
    'stranded'=> {:v=>3},
     'stuck'=> {:v=>3,'not'=>2},
    'unfuckingbelievable'=> {:v=>1},
    'awesome'=> {:v=>7},
    'rocking'=> {:v=>5},
    'amazing '=> {:v=>7},
   'שמח'=> {:v=>5,'מאוד'=>6,'ממש'=>6,'לא'=>3},
   'שמחה'=> {:v=>5,'מאוד'=>6,'ממש'=>6,'לא'=>3},
   'מאושר'=> {:v=>7,'לא'=>3},
   'מאושרת'=> {:v=>7,'לא'=>3},
   'כיף'=> {:v=>5,'מאוד'=>6,'ממש'=>6,'לא'=>3},
   'נהדר'=> {:v=>5,'מאוד'=>6},
   'נפלא'=> {:v=>7},
   'תענוג'=> {:v=>7},
   'סבבה'=> {:v=>5},
   'משעשע'=> {:v=>6,'לא'=>4},
   'משועשע'=> {:v=>6,'לא'=>4},
   'משועשעת'=> {:v=>6},
   'מצחיק'=> {:v=>6,'מאוד'=>6,'ממש'=>6,'לא'=>4},
   'צחוקים'=> {:v=>6},
   'טוב'=> {:v=>5,'מאוד'=>5,'ממש'=>5,'לא'=>3},
   'מעולה'=> {:v=>5,'מאוד'=>6,'ממש'=>6},
   'עצוב'=> {:v=>3,'מאוד'=>2,'ממש'=>2,'לא'=>4},
   'עצובה'=> {:v=>3,'מאוד'=>2,'ממש'=>2,'לא'=>4},
   'באסה'=> {:v=>3,'מאוד'=>2,'ממש'=>2,'לא'=>4},
   'בעסה'=> {:v=>3,'מאוד'=>2,'ממש'=>2,'לא'=>4},
   'מבואס'=> {:v=>3,'מאוד'=>2,'ממש'=>2,'לא'=>4},
   'מבואסת'=> {:v=>3,'מאוד'=>2,'ממש'=>2,'לא'=>4},
   'מבועס'=> {:v=>3,'מאוד'=>2,'ממש'=>2,'לא'=>4},
   'מבועסת'=> {:v=>3,'מאוד'=>2,'ממש'=>2,'לא'=>4},
   'מדוכדך'=> {:v=>3,'מאוד'=>2,'ממש'=>2},
   'מדוכדכת'=> {:v=>3,'מאוד'=>2,'ממש'=>2},
   'נמאס'=> {:v=>1},
   'אוהב'=> {:v=>5,'מאוד'=>5,'ממש'=>5,'לא'=>3},
   'אוהבת'=> {:v=>3,'מאוד'=>2,'ממש'=>2,'לא'=>3},
   'מתגעגע'=> {:v=>3,'מאוד'=>2,'ממש'=>2,'לא'=>4},
   'מתגעגעת'=> {:v=>3,'מאוד'=>2,'ממש'=>2,'לא'=>4},
   'גרוע'=> {:v=>3,'מאוד'=>2,'ממש'=>2,'לא'=>4},
   'רע'=> {:v=>3,'מאוד'=>2,'ממש'=>2,'לא'=>4},
   'בסדר'=> {:v=>4,'מאוד'=>4,'ממש'=>4,'לא'=>3},
   'אוקיי'=> {:v=>4},
   'יפה'=> {:v=>5,'מאוד'=>5,'ממש'=>5,'לא'=>3},
   'חולה'=> {:v=>3,'מאוד'=>3,'ממש'=>3}







}

